version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    
    # Primary container image where all commands run
    
    docker:
      - image: circleci/python:3.6.2-stretch-browsers


    # Service container image
    
      - image: circleci/postgres:9.6.5-alpine-ram
        environment:
          POSTGRES_USER: post_user
          POSTGRES_DB: post_db
          POSTGRES_PASSWORD: password


    steps:
      - checkout
      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client-9.6
      - run: whoami
      - run: |
          psql \
          -c "CREATE database test1;"
      - run: |
          psql \
          -d test1 \
          -c "CREATE TABLE test (name char(25));"
      - run: |
          psql \
          -d test1 \
          -c "INSERT INTO test VALUES ('John'), ('Joanna'), ('Jennifer');"
      - run: |
          psql \
          -d test1 \
          -c "SELECT * from test"
      - run:
          sudo pip3 install psycopg2 
      - run:    
          python app.py







workflows:
  main:
    jobs:
      - build-and-test
